### ISSUE TITLE
Constant read user data

### ISSUE THREAD

**Issue by Carolebins** [sparkfun/Simultaneous_RFID_Tag_Reader#4]
Hello,

for my master thesis I work with the sparkfun simultaneous Rfid reader and  I try to create a constant read program that outputs the user data. Could someone help me with that?

Many thanks in advance and best regards

Carole

**Comment by nseidle** [comment]
Hi Carole,

This repo is for issues with the hardware. For general project support I recommend the SparkFun forums: https://forum.sparkfun.com/

**Comment by Mariyah1** [comment]
Hello Carolebins,
Any way in which we can communicate with you? We have a similar issue and I would appreciate it
Thanks
