### ISSUE TITLE
Send a standard Class−1 Generation−2 UHF Select command

### ISSUE THREAD

**Issue by Holy1990** [sparkfun/Simultaneous_RFID_Tag_Reader#7]
I need to read the temperature from my RFID temperature sensor. For reading the temperature, 2 step process requiring standard UHF Select and Read commands.

1. Send a **standard Class−1 Generation−2 UHF Select command** with the parameters described in Table 6 to initialize the temperature sensor and calculate a Temperature Code. The Select command to be followed by 2 ms of continuous wave before the reader issues any further commands. This pause
gives the temperature sensor circuit time to run. The reader must not power down at any time between the Select and Read commands.

2. Send a standard Class−1 Generation−2 UHF Read command to retrieve the Temperature Code from the sensor tag memory at the location given in Table 7.

 Is this SparkFun Simultaneous RFID Tag Reader Library  for Arduino support to send the **Select command**? i only able to send the read command follow the example provided by sparkfun on Arduino.

**Comment by nseidle** [comment]
Thanks for posting! And you did get the issue posted [on the lib repo](https://github.com/sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library/issues/12) where it is best. I'm closing this one because it's a duplicate.
