### ISSUE TITLE
Read multiple tags at once

### ISSUE THREAD

**Issue by adambadge** [sparkfun/Simultaneous_RFID_Tag_Reader#9]
Hello,

Quick question regarding multiple tag reads.

I have loaded up example sketch 1 and it works great with a single tag and works pretty well. Multiple tags in a sheet of 5 I start to get "Bad CRC" errors Is the Arduino examples sketches designed to provide simultaneous tag scanning capability similar to that of the universal assistant app? 

Regards,
Adam

<img width="875" alt="Screen Shot 2021-04-01 at 11 43 54 am" src="https://user-images.githubusercontent.com/22568827/113227959-8e700380-92df-11eb-9c37-f5c3b8f2f331.png">

**Comment by nseidle** [comment]
I suspect it's related to software serial dropping or corrupting characters. Try using a micro with a hardware serial port and let us know if you continue seeing the issue.
